### ISSUE TITLE
Suggestions:

### ISSUE THREAD

**Issue by rexkix** [ashbash1987/ktanemod-modselector#1]
1. Add a "Merge" function to the Load dialog.
Merging a profile with the current profile would add in whatever modules a profile can do that the existing profile can not.  This would be for situations where you have two experts and want to have a combined profile that enables anything either guy can do.  I guess you'd go through any mods that are currently vetoed and remove the veto if it's not also in the merged profile.

2. Simple improvements to the Save dialog:
- Make the text field be selected when the interface is brought up.
- Make <return> be the same as the Save button

3. Less simple improvements to the Save dialog:
Let the user select a filename (just like the Load or Delete options) and have this populate the Filename field.  From typing mistakes, I'll often save a file under a slightly different name and wonder which one was the most up-to-date version.

4. Super impressive improvements, but perhaps less important features to the Save functionality:
Remember which profile was loaded last.  Add a "Save" button that saves any changes made to that profile.  Add a "Save As" button that acts like the current Save button.

Thanks Ash. :)

**Comment by ashbash1987** [comment]
Broken this issue down into multiple issues to follow individual progress of tasks more easily. Closing this issue now.
