### ISSUE TITLE
Group Union and Intersection profiles

### ISSUE THREAD

**Issue by rexkix** [ashbash1987/ktanemod-modselector#10]
Right now, I'm prefixing my Union profiles with "zzz" so they're at the bottom.  Please group them at the bottom naturally so I don't have to do this.  Thanks. :)

**Comment by ashbash1987** [comment]
Sure, can re-sort by group.

**Comment by ashbash1987** [comment]
Now grouped by operation first, then by name in commit c2e71b5caab9044623222934208e6b514fe7d3fb.
