### ISSUE TITLE
Show Union profiles differently than Intersection profiles

### ISSUE THREAD

**Issue by rexkix** [ashbash1987/ktanemod-modselector#11]
Consider making a visual cue distinguishing Intersection profiles from Union profiles.  I like the monotone interface, but maybe you can shade them differently.

**Comment by ashbash1987** [comment]
I did originally have the intersect and union symbols at the front of the profile name, but it didn't look too good. Maybe just having them slightly tinted one way of the other will be a strong-enough visual cue.

**Comment by ashbash1987** [comment]
As of commit c2e71b5caab9044623222934208e6b514fe7d3fb, Interesection profiles will have a slight orange-ish pastel tint applied to them, and Union profiles will have a slight green-ish pastel tint applied to them.
