### ISSUE TITLE
Make the tablet support other systems (modules, services, etc.)

### ISSUE THREAD

**Issue by rexkix** [ashbash1987/ktanemod-modselector#12]
Please make the tablet support other modules.  I know Mission Maker wants to use it.

**Comment by ashbash1987** [comment]
Would need to declutter my current work on Mod Selector, and see what can be extracted out for re-use in external mods.

**Comment by rexkix** [comment]
So, would it be a library of functions that also work with the tablet?  If the tablet isn't there already, this API would first create it?

I thought it was going to be a collection of services the Mod Selector provides to other modules.  If Mod Selector isn't there, then the other modules would have to know to do nothing or to deploy their "alternative interface" if they've even got one, which they probably don't.  Certainly the log file would give appropriate error messages.

If I'm right at what you intend, then it's way better than what I was thinking was going to happen.

**Comment by ashbash1987** [comment]
The ultimate goal would be something that could always re-build the tablet if it's not there from another mod package, but I don't see getting to that point any time soon. For the time being, being a dependency on mod selector isn't all too bad (currently serving to 3.5k+ subscribers), but if popular opinion wants the API in a separate mod on the workshop that also has to be installed, then that might be doable, would just take longer.

There's two ways of potentially implementing this:
1. Provide a strict API that has pre-designed layouts, and the other mod package calls to show a specific layout with content and hooks up to events to achieve what they need to. With this route, other mods would be limited to the layouts that are exposed by the API; the mods wouldn't have a say in any way about how the UI is shown (i.e. if they wanted a pie chart or something that is completely different to the grid layouts presented before)
2. Provide a basic API that essentially forces the UI layout and design upon the external mod package developer. All that would be given at the setup stage API-wise is a list/array of GameObjects, to which the tablet UI would just show/hide blindly by the external mod. There'd be no validation/verification that they're doing the right thing, but there would be ultimate flexibility to do whatever UI design they wanted.

**Comment by ashbash1987** [comment]
Currently gone down the route of option 2 - using a cross-mod API to provide some simple methods to add pages to the mod selector page manager.
