### ISSUE TITLE
Change Union profiles to make them be more "logical"

### ISSUE THREAD

**Issue by rexkix** [ashbash1987/ktanemod-modselector#13]
How Union profiles work is counter-intuitive.  I get it now.  Right now, I've got a profile with name "No Quad Decker" with all the Quad Decker cases disabled.  To enable Quad Decker cases, I have to disable my "No Quad Decker" profiler, a double negative.  Instead, I'd prefer to have a "Quad Decker" profile that I enable.

I've got a really wacky way to "fix" this, but I doubt you're going to like it.  I think it works, but I'm not even sure.  The idea is to flip everything on it's head.  The user still creates a Union profile as they did before, but instead of thinking of selected items as being disabled, they think of them as being enabled.  The Mod Selector then enables all Union profiles when they are unselected and disables them when they are selected.  This way if a Union profile includes a thing, then it is excluded when that profile is unselected and included when that profile is selected.

Irrespective of whether this is a change you can accept, does this scheme actually work?  And as I said, I fully expect you to reject this as an undesirable idea anyway.

**Comment by rexkix** [comment]
Wait.  I think this IS a bad idea now.  It's great for my bomb casing list, but it doesn't work so well with a list of mods a defuser doesn't want to defuse.

**Comment by ashbash1987** [comment]
It is feasible, yes, but with regards to whether I think it's a good idea or not, I think it's not great. Having profiles change the active state of elements when the profiles are not active is completely counter-intuitive to me.

I can understand where you're trying to come from, but it seems a bit haphazard having the union profile set inclusion logic flipped based on the profile's active state. As you also suggest in the follow-up comment, it doesn't work too well when you then have to look at the intersect lists.

From the outset, Mod Selector was just trying to mirror the 'veto' options design, just expanded out further and somewhat saveable and configurable. As long as users understand that the profiles are just an extension of being 'veto' lists (i.e. they disable things), I don't think there's much confusion in having to deactivate a 'No Quad Decker' profile to enable quad deckers.

I'll leave this issue open if you've got any other possible ideas to improve this situation.

**Comment by rexkix** [comment]
Okay, I have another dumb idea.  Sorry about that.

What if you introduced another kind of Union profile that behaves as I described above.  We've not got Intersection profiles ("Intersection"), Union profiles ("Always disable"), and the new kind ("Always enable").  Of course, the new kind would be implemented as a kind of Union profile as I described.

But, am I really serious about this?  How does introducing another kind of profile make things simpler?  Frankly, I'm just hoping this bad idea helps spawn a good idea, but I kind of doubt it.

Regardless, "Hi Ash". :)

**Comment by ashbash1987** [comment]
The problem I see in having a categorisation of "Always disable" and a categorisation of "Always enable" is in the priority-ordering of the two.

For the case of intersections and unions, it seemed sensible to me to do the ordering as intersections, then unions. In terms of ordering of 'unions' and 'reverse unions', what should be the expected ordering? Should 'always enable' always override 'always disable', or should it be the other way round? The answer to this question doesn't seem nearly as obvious to me as was the case for intersect w/ union.

Or does there need to be a priority ordering value for each profile that would dictate the order of combination? (At which point, the profile merging gets stupidly convoluted for the end-user!)

**Comment by bmn** [comment]
Isn't "always enable" basically what Intersection does anyway? I know from a technical standpoint it's "disable this only if every other Intersection disables it too", but personally I find it more intuitive to think of it as "force enable this, except if a Union disables it".

**Comment by ashbash1987** [comment]
Leaving it the way it was for the time being.
