### ISSUE TITLE
Change titles on Set Active Profiles and Edit Profile pages

### ISSUE THREAD

**Issue by rexkix** [ashbash1987/ktanemod-modselector#16]
The title on the Set Active Profiles page is "Select Profiles".  The title on the Edit Profiles page is "Select Profile".  I know one is plural and one is singular, but this is subtle. Perhaps change the first to "Select Profiles to Activate" or simply "Activate Profile", and the second to "Select Profile to Edit" or "Edit Profile".  As it is, the Delete Profile page says "Delete Profile".

**Comment by ashbash1987** [comment]
Changed in commit c2e71b5caab9044623222934208e6b514fe7d3fb.
