### ISSUE TITLE
Trying to Create a new profile with an existing profile's name...

### ISSUE THREAD

**Issue by rexkix** [ashbash1987/ktanemod-modselector#19]
On my computer, trying to create a new profile with an existing profile's name does nothing.  I think it might be better if there was an error message at the top of the screen. Or maybe not. I did use the word "might".

**Comment by ashbash1987** [comment]
I definitely want an error message; I just wanted to get the mod selector out initially, so yes this will be a thing

**Comment by ashbash1987** [comment]
Returning back to this bug - will be implemented when the 'toast' message thing gets added.

**Comment by ashbash1987** [comment]
This is now implemented.
