### ISSUE TITLE
Add tags to logging

### ISSUE THREAD

**Issue by rexkix** [ashbash1987/ktanemod-modselector#21]
It looks as if the Mod Selector logs, but not with tags.  Please add tags.

**Comment by ashbash1987** [comment]
What would be the reason for me to add tags to Mod Selector?

**Comment by rexkix** [comment]
Sometimes you think a mod should be disabled but it's not.  I saw others get into this problem twice today.  I thought logging might help people debug their profiles.

From what I've seen, usually it's an Intersection / Union problem.  Probably the existing logging wouldn't help that and more would be huge hassle.  It's not a big deal.

**Comment by ashbash1987** [comment]
Adding tags doesn't really help solve the problem you're detailing. It may increase visibility of the mod selector logs amongst the myriad logging from other sources, but that isn't the real solution to this problem. 

Having to use the log to resolve personal issues is completely wrong. It's the wrong tool to use. It just increases the barrier to entry to stupid levels. The log is useful as a developer for debugging information; it's not really there for lay users to be using actively. 

The real solution would be UI in the mod selector that displayed what the current profile selection would do, and also how each mod element was disabled (if it was from a complete intersection, or from a union, etc.). A solution like that would be far more immediate and visually more attractive than a wall of text.
