### ISSUE TITLE
When profile name contains a blank, for some users it changes it to a "_" character

### ISSUE THREAD

**Issue by rexkix** [ashbash1987/ktanemod-modselector#22]
When Cooldude and Alex make a profile with a space in it, they get that replaced by an underscore ("_").  When I do the same, I don't.

Most strange.

**Comment by ashbash1987** [comment]
That is indeed strange. I can't yet determine anything obvious or trivial in the code that could cause this behaviour. I'd need to know the strings they tried, ultimately the full path where the profiles are going, and also the OS and version of OS they're currently running on.

**Comment by rexkix** [comment]
You might ask Cooldude.  His profile had that issue.

**Comment by ashbash1987** [comment]
Talked to Cooldude, there's no issue with Mod Selector here. What happens is he creates a profile with spaces in (which will also put spaces in the local filename), and when sharing that profile over Discord, Discord will convert the filename to have underscores in-place of the space (over the web, a standard 'space' character in a URL gets converted to %20, so I guess the Discord devs decided to replace spaces with underscores to ensure the file links still look somewhat human-readable).

In any case, this is not the fault of Mod Selector.

**Comment by rexkix** [comment]
Of course.  I should have thought of it.  You might make Mod Selector interpret an “_” as a space for this reason.  Or maybe not.  You are possibly allowing special characters.  What if the person meant to type an underscore?

It’s fine the way it is.
