### ISSUE TITLE
Consider adding a "Go to ModProfiles Directory" option

### ISSUE THREAD

**Issue by rexkix** [ashbash1987/ktanemod-modselector#24]
I am not sure I like this, but I'm also not sure I don't.  This one is up to you.

As you can see, I'm exchanging profiles with others, but I am having a super hard time getting people to find their ModProfiles folder.  We've got Main Menu options to find the Manual and ModSettings folders.  Why not have the Mod Selector give people an easy way to get to the ModProfiles directory?

**Comment by ashbash1987** [comment]
Added in commit 985bb31ca8ac1a553c98ecc8618c7ae319d91920.
