### ISSUE TITLE
Re-read the ModProifles directory when something changes

### ISSUE THREAD

**Issue by rexkix** [ashbash1987/ktanemod-modselector#27]
Now that people are exchanging profiles, the first thing they ask is, "What do I have to do to see the new profile?"  The answer is to restart the game.

It would be nicer if Mod Selector noticed when the ModProfiles directory changes.  This is a super minor thing, just a total wishlist item, and not even a much wanted one at that.

**Comment by ashbash1987** [comment]
Now actively monitors the ModProfiles directory for changes (new files, updates, renames, deletes).
