### ISSUE TITLE
VR (Motion Control) Support

### ISSUE THREAD

**Issue by GrinningCheetah** [ashbash1987/ktanemod-modselector#33]
Works on my pc, but on VR, if you drop the tablet, it falls through the desk and floor. If you throw it away, it doesn't respawn. Finally, you cannot select  anything with motion controllers. I tested this on my friend's HTC Vive. Please try and fix these problems, because it is such a useful addition.

**Comment by ashbash1987** [comment]
Ok, I'll try to make the colliders bigger for the UI elements. And I'll also look to add a rigidbody collider to the entire tablet (I thought I had previously done that, but possibly not). As I have no kit to test this, I'll be making changes entirely in the blind.
