### ISSUE TITLE
Does not go to Mod Profiles folder on a Mac

### ISSUE THREAD

**Issue by rexkix** [ashbash1987/ktanemod-modselector#40]
Apparently, the "Go to Mod Profiles Folder" button doesn't work on a Mac.

**Comment by RoyalFlush411** [comment]
Seconded. Left a comment on Steam Page too, but on Mac, the tablet will only be able to be selected intermittently. It appears on the set-up page and can be highlighted sometimes but most of the time won't be able to be picked up so cannot access any of the mod editing options. Not sure if it's a compatibility clash with another mod?

**Comment by ashbash1987** [comment]
Crossing out unrelated part of that comment. After discussion, unrelated issue might be due to issues with other specific mods.

**Comment by ashbash1987** [comment]
@rexkix Had another quick look yesterday, doesn't appear to be any suitable way of achieving this due to permissions. Does the MacOS version of the game support opening the mod settings folder from the mods brochure in the setup scene? If it does, then I might need to perloin SCG's code for that.

**Comment by ashbash1987** [comment]
Managed to get a hold of the Mac version of the game, they do support some way of opening mod folders; posting the code snippet here for my benefit later:
```cs
Process process = Process.Start("open", "-n -R \"" + path + "\"");
```
