### ISSUE TITLE
When creating a new profile, make the Return key be the same as the Create button

### ISSUE THREAD

**Issue by rexkix** [ashbash1987/ktanemod-modselector#43]
When creating a new profile, make the Return key be the same as the Create button

**Comment by ashbash1987** [comment]
@rexkix I believe this was done in b8f20dd2344059f6e745387b672f1b6443b48ab8?

**Comment by rexkix** [comment]
As it happens, yes.  I don't know why I saw otherwise, but I claim I did, else I wouldn't have opened the issue.  I'll close it now.
