### ISSUE TITLE
VR Motion Controllers can't go back a page.

### ISSUE THREAD

**Issue by TheDrawingCoder-Gamer** [ashbash1987/ktanemod-modselector#57]
When using the Vive you can't go back a page as there's no visible button. (And I would assume Oculus players have the same issue)
It would be nice to maybe see a home button on the tablet?
This is why all of the vanilla menus have a back button because VR players need a button to press.
Also would be nice to see the tablet get a bit bigger in VR mode to help with seeing, as texts gets blurry in VR.

**Comment by ashbash1987** [comment]
Fixed in c13635e26b6be090781dc2b4c61c6c7ca90a6a8a
