### ISSUE TITLE
Make Widget Expander be enableable and disableable

### ISSUE THREAD

**Issue by rexkix** [ashbash1987/ktanemod-modselector#8]
Right now, it seems that Widget Expander is enabled at game startup.  This means that disabling Widget Expander it in the Mod Selector doesn't work.

Please make it work.  Thank you.

**Comment by rexkix** [comment]
Please allow special characters in profile names.  I know your onscreen keyboard doesn't have a button for special keys.  Either add it or at least allow the the user to enter them from a physical keyboard.

**Comment by ashbash1987** [comment]
This will be a Widget Expander implementation; it's not an implementation for Mod Selector to achieve (I forgot it's already a raised issue over on that repository: https://github.com/ashbash1987/ktanemod-widgetrecount/issues/1)
