### ISSUE TITLE
Allow special characters in profile names

### ISSUE THREAD

**Issue by rexkix** [ashbash1987/ktanemod-modselector#9]
Please allow special characters in profile names. I know your onscreen keyboard doesn't have a button for special keys. Either add it or at least allow the the user to enter them from a physical keyboard.

**Comment by ashbash1987** [comment]
I have to be careful as to which special characters to use, as the name is used verbatim as the file name for the profile, and certain symbols are not allowed as part of filenames.
I'll need to either:
- have the profiles save as a machine-friendly name and have a separate human name which can support all of the special symbols, or
- reduce the subset of special characters to allow to those that are allowable in filenames.

**Comment by rexkix** [comment]
Either way.  I wanted to control sorting, so I prefixed some profiles I wanted at the end of the list with "zzz".  I was thinking special characters might be good for that kind of thing.  Frankly, that's a kludge.  What I really want is the grouping of Union and Intersection profiles.
